###
## This is the place to override the swaggercookbook's default attributes.
##
## Do not edit THIS file directly. Instead, create
## "swagger/attributes/customize.rb" in your cookbook repository and
## put the overrides in YOUR customize.rb file.
####
#
##
